config/routes.rb
Rails.application.routes.draw do

  resources :lists do
    resources :items
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :description, :quantity, presence: true
  validates :description, length: { maximum: 255 }
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  def to_s
    description
  end
end

app/models/list.rb
class List < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  validate :expires_at_is_not_in_the_past


  def to_s
    name
  end

  protected

  def expires_at_is_not_in_the_past
    if expires_at && expires_at < Date.today
      errors.add :expires_at, :invalid
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_list
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items
  def index
    @items = @list.items
  end

  # GET /items/1
  def show; end

  # GET /items/new
  def new
    @item = @list.items.new
  end

  # GET /items/1/edit
  def edit; end

  # POST /items
  def create
    @item = @list.items.new(item_params)

    if @item.save
      redirect_to list_items_path(@list), notice: "Item was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to list_items_path(@list), notice: "Item was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to list_items_path(@list), notice: "Item was successfully destroyed."
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = @list.items.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:list_id, :description, :quantity, :completed)
    end
  
    def set_list
      @list = List.find(params[:list_id])
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  # GET /lists
  def index
    @lists = List.all
  end

  # GET /lists/1
  def show; end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit; end

  # POST /lists
  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /lists/1
  def update
    if @list.update(list_params)
      redirect_to @list, notice: "List was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /lists/1
  def destroy
    @list.destroy
    redirect_to lists_url, notice: "List was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:name, :expires_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: [@list, item]) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :list_id, style: "display: block", :class => 'form-label' %>
    <%= form.text_field :list_id, :class => 'form-control', style: "width: 25%" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, style: "display: block", :class => 'form-label'%>
    <%= form.text_field :description, :class => 'form-control', style: "width: 25%"%>
  </div>

  <div class="mb-3">
    <%= form.label :quantity, style: "display: block", :class => 'form-label'%>
    <%= form.number_field :quantity, :class => 'form-control', style: "width: 25%"%>
  </div>

  <div class="mb-3">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>">
  <p>
    <strong>List:</strong>
    <%= item.list_id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= item.description %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= item.quantity %>
  </p>

  <p>
    <strong>Completed:</strong>
    <%= item.completed %>
  </p>

</div>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Show this item", [@list, @item] %> |
  <%= link_to "Back to items", list_items_path(@list) %>
</div>

app/views/items/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Items of <%= @list %></h1>

<div id="items">
  <% @items.each do |item| %>
    <%= render item %>
    <p>
      <%= link_to "Show this item", [@list, item] %>
    </p>
  <% end %>
</div>

<%= link_to "New item", new_list_item_path(@list) %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render "form", item: @item %>

<br>

<div>
  <%= link_to "Back to items", list_items_path(@list) %>
</div>

app/views/items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @item %>

<div>
  <%= link_to "Edit this item", edit_list_item_path(@list, @item) %> |
  <%= link_to "Back to items", list_items_path(@list) %>

  <%= button_to "Destroy this item", [@list, @item], method: :delete , :class => 'btn btn-sm btn-danger mt-3' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingLists</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :expires_at, style: "display: block" %>
    <%= form.date_field :expires_at %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div id="<%= dom_id list %>">
  <p>
    <strong>Name:</strong>
    <%= list.name %>
  </p>

  <p>
    <strong>Expires at:</strong>
    <%= list.expires_at %>
  </p>

  <p>
    <strong>#Items:</strong>
    <%= list.items.count %>
  </p>

</div>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Show this list", @list %> |
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lists</h1>

<div id="lists">
  <% @lists.each do |list| %>
    <%= render list %>
    <p>
      <%= link_to "Show this list", list %>
    </p>
  <% end %>
</div>

<%= link_to "New list", new_list_path %>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render "form", list: @list %>

<br>

<div>
  <%= link_to "Back to lists", lists_path %>
</div>

app/views/lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list %>

<p>
  <ul>
      <% @list.items.each do |item| %>
        <li>
          <%= item %>
          <%= ' X' if item.completed? %>
        </li>
      <% end %>
  </ul>
</p>

<div>
  <%= link_to "Edit this list", edit_list_path(@list) %> |
  <%= link_to "Items details for this list", list_items_path(@list) %> |
  <%= link_to "Back to lists", lists_path %>

  <%= button_to "Destroy this list", @list, method: :delete %>
</div>